# -*- coding: utf-8 -*-
"""geo_engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import pandas as pd

def charger_sites():

    data={
    "Site":[
    "Dakar Arena",
    "Iba Mar Diop",
    "Expo Center",
    "Saly Beach"
    ],
    "Latitude":[14.73,14.72,14.74,14.45],
    "Longitude":[-17.20,-17.46,-17.21,-17.00]
    }

    return pd.DataFrame(data)