# -*- coding: utf-8 -*-
"""ia_matching

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import pandas as pd

def score_matching(vol,mis):

    score=0

    if vol.get("Ville")==mis.get("Ville"):
        score+=3

    if vol.get("Competence")==mis.get("Sport"):
        score+=5

    return score


def matching_volontaires(vol_df,mis_df):

    results=[]

    for _,v in vol_df.iterrows():

        best=None
        best_score=-1

        for _,m in mis_df.iterrows():

            s=score_matching(v,m)

            if s>best_score:

                best_score=s
                best=m["Sport"]

        results.append({
        "Volontaire":v.get("Nom",""),
        "Mission":best,
        "Score":best_score
        })

    return pd.DataFrame(results)