# -*- coding: utf-8 -*-
"""optimisation_volontaires

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import pandas as pd

def taux_couverture(df):

    total_requis=df["Volontaires_requis"].sum()
    total_actuels=df["Volontaires_actuels"].sum()

    return round((total_actuels/total_requis)*100,2)


def analyse_effectifs(df):

    df["Sous_effectif"]=df["Volontaires_actuels"]<df["Volontaires_requis"]

    df["Manque"]=df["Volontaires_requis"]-df["Volontaires_actuels"]

    df["Manque"]=df["Manque"].apply(lambda x:max(x,0))

    return df