# -*- coding: utf-8 -*-
"""smart_alerts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import pandas as pd

def detect_incident(df):

    seuil=df["Flux"].mean()*1.5

    df["Alerte"]=df["Flux"]>seuil

    return df