# -*- coding: utf-8 -*-
"""auth

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st

USERS = {
"admin":"joj2026",
"operations":"smartayo",
"command":"center"
}

def login():

    st.sidebar.title("Connexion")

    username = st.sidebar.text_input("Utilisateur")
    password = st.sidebar.text_input("Mot de passe",type="password")

    if st.sidebar.button("Connexion"):

        if username in USERS and USERS[username]==password:
            st.sidebar.success("Connexion réussie")
            return username
        else:
            st.sidebar.error("Accès refusé")

    return None