# -*- coding: utf-8 -*-
"""config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

APP_TITLE="SMART-AYO JOJ Dakar 2026"

DATA_FILES={
"calendrier":"calendrier_sports.xlsx",
"flux":"flux.xlsx",
"sites":"sites.xlsx",
"transports":"transports.xlsx",
"volontaires":"volontaires.xlsx"
}