# -*- coding: utf-8 -*-
"""database

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import pandas as pd
import os

DATA_PATH="data"

def load_excel(file):

    path=os.path.join(DATA_PATH,file)

    if os.path.exists(path):

        return pd.read_excel(path)

    return pd.DataFrame()