# -*- coding: utf-8 -*-
"""10_Impact_Durable

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
import pandas as pd

st.title("Impact Durable")

data = {
"Indicateur":[
"Déplacements évités",
"Energie optimisée",
"CO2 évité",
"Optimisation transports"
],
"Valeur":[30,25,40,35]
}

df = pd.DataFrame(data)

st.dataframe(df)

st.metric("Score durable global",df["Valeur"].sum())