# -*- coding: utf-8 -*-
"""1_Dashboard_Strategique

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
import plotly.express as px
from database import load_excel
from config import DATA_FILES

st.title("Dashboard Stratégique")

cal = load_excel(DATA_FILES["calendrier"])
sites = load_excel(DATA_FILES["sites"])
flux = load_excel(DATA_FILES["flux"])

c1,c2,c3,c4 = st.columns(4)

c1.metric("Sports",cal["Sport"].nunique())
c2.metric("Sites",sites["Site"].nunique())
c3.metric("Flux transport",flux.shape[0])
c4.metric("Villes",sites["Ville"].nunique())

sport_count = cal.groupby("Sport").size().reset_index(name="Sessions")

fig = px.bar(sport_count,x="Sport",y="Sessions")

st.plotly_chart(fig,use_container_width=True)