# -*- coding: utf-8 -*-
"""2_Calendrier_Operationnel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
from database import load_excel
from config import DATA_FILES

st.title("Calendrier Opérationnel")

df = load_excel(DATA_FILES["calendrier"])

st.dataframe(df)

sport = st.selectbox("Filtrer par sport",["Tous"]+list(df["Sport"].unique()))

if sport!="Tous":

    st.dataframe(df[df["Sport"]==sport])