# -*- coding: utf-8 -*-
"""3_Sites_Sportifs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
import plotly.express as px
from database import load_excel
from config import DATA_FILES

st.title("Sites Sportifs")

df = load_excel(DATA_FILES["sites"])

st.dataframe(df)

fig = px.histogram(df,x="Ville")

st.plotly_chart(fig,use_container_width=True)