# -*- coding: utf-8 -*-
"""4_Gestion_Volontaires

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
from database import load_excel
from config import DATA_FILES

st.title("Gestion des Volontaires")

df = load_excel(DATA_FILES["volontaires"])

st.dataframe(df)

nom = st.text_input("Recherche volontaire")

if nom:

    res = df[df["Nom"].str.contains(nom,case=False)]

    st.dataframe(res)