# -*- coding: utf-8 -*-
"""5_Matching_IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
from database import load_excel
from config import DATA_FILES
from modules.ia_matching import matching_volontaires

st.title("Matching IA Volontaires")

vol = load_excel(DATA_FILES["volontaires"])
missions = load_excel(DATA_FILES["calendrier"])

match = matching_volontaires(vol,missions)

st.dataframe(match)