# -*- coding: utf-8 -*-
"""8_Incidents_Terrain

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
import pandas as pd

st.title("Incidents Terrain")

data={
"Site":["Dakar Arena","Expo Center","Saly Beach"],
"Type":["Sécurité","Technique","Logistique"],
"Niveau":["Faible","Moyen","Critique"]
}

df=pd.DataFrame(data)

st.dataframe(df)

if st.button("Envoyer alerte"):

    st.warning("Alerte envoyée au centre de commandement")