# -*- coding: utf-8 -*-
"""9_Command_Center

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
import plotly.express as px
import numpy as np
import pandas as pd

st.title("SMART-AYO Command Center")

c1,c2,c3=st.columns(3)

# écran 1 flux

df=pd.DataFrame({
"zone":["Dakar","Diamniadio","Saly"],
"flux":[12000,15000,7000]
})

fig1=px.bar(df,x="zone",y="flux",title="Flux spectateurs")

c1.plotly_chart(fig1,use_container_width=True)

# écran 2 transport

df2=pd.DataFrame({
"systeme":["TER","A1","Navettes","Aéroport"],
"performance":[90,85,88,92]
})

fig2=px.bar(df2,x="systeme",y="performance")

c2.plotly_chart(fig2,use_container_width=True)

# écran 3 incidents

df3=pd.DataFrame({
"niveau":["faible","moyen","critique"],
"nombre":[5,3,1]
})

fig3=px.pie(df3,names="niveau",values="nombre")

c3.plotly_chart(fig3,use_container_width=True)

st.success("Centre opérationnel actif")