# -*- coding: utf-8 -*-
"""9_Smart_City_Command_Center

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-9dZBsm8iQq8aGa_2WndG2OCJH8nyx2
"""

# -*- coding: utf-8 -*-

import streamlit as st
import plotly.express as px
from database import load_excel
from config import DATA_FILES

st.title("Smart City Command Center")

df = load_excel(DATA_FILES["flux"])

fig = px.bar(
df,
x="Mode",
y="Volume_estime",
color="Criticite_operationnelle"
)

st.plotly_chart(fig,use_container_width=True)